### ISSUE TITLE
Videos stuck downloading on 0% - white background on preview 

### ISSUE THREAD

**Issue by SimonSKang** [rie-kumar/MusicVideoPlayer#15]
Videos are stuck at 0% when downloading, and when you preview, they appear white.

**Comment by b-rad15** [comment]
I have heard of this happening when the cpu is at 100% but have never been able to reproduce it

**Comment by b-rad15** [comment]
Possible fix elevating youtube-dl process priority

**Comment by b-rad15** [comment]
temp fix, cancel and restart
