### ISSUE TITLE
Search usually shows no results

### ISSUE THREAD

**Issue by SenseiPSK** [rie-kumar/MusicVideoPlayer#16]
Most times the video search will show no results. Maybe 1 out of every 20 times of starting Beat Saber the search will work normally. It was working fine but something suddenly changed maybe 2 weeks ago.

**Comment by gthgame** [comment]
search not working anymore ...

**Comment by Kylon99** [comment]
I took a quick look at the issue and it seems that the search results are coming back with most of the data as a big block of JSON in a <script /> section now.  It looks like it's in the \<body \/\> but in a <script /> section in there with the first part of the JSON as
```
<script>
        window["ytInitialData"] = ...
```
I modified the mod to log the search results and I saved and formatted the HTML and the JSON.
[Test.zip](https://github.com/rie-kumar/MusicVideoPlayer/files/4888579/Test.zip)

This is the search URL I used:
[https://www.youtube.com/results?search_query=Unforgettable%20-%20Nat%20King%20Cole](url)

Inside the JSON, the results are there and I believe we can use change the code to parse that instead and get the required data.  Within the JSON, the section that starts with:
```
"videoRenderer": {
    "videoId": "jFHr2ghOx6A",
```
contains all the thumbnails and video IDs we need.  I think.

**Comment by mcastilloweb** [comment]
[INFO @ 08:20:43 | Music Video Player] ERROR: can't find the current version. Please try again later.

**Comment by mcastilloweb** [comment]
[INFO @ 08:20:41 | Music Video Player] Has ffmpeg -> Will download and mux audio and video
[DEBUG @ 08:20:41 | Music Video Player] OnLoad: ScreenManager
[INFO @ 08:20:43 | Music Video Player] ERROR: can't find the current version. Please try again later.
[INFO @ 08:20:43 | Music Video Player] Youtube-DL update complete
[DEBUG @ 08:20:43 | Music Video Player] Has Loaded: 
[DEBUG @ 08:20:43 | Music Video Player] Video is: Download Progress: Unknown
[DEBUG @ 08:20:43 | Music Video Player] Selected Level: Juicy
[DEBUG @ 08:20:48 | Music Video Player] Has Loaded: 
[DEBUG @ 08:20:48 | Music Video Player] Video is: Download Progress: Unknown
[INFO @ 08:20:50 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:20:51 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:20:53 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:20:54 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:20:56 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:20:57 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:20:58 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:20:59 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:21:00 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:21:00 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:21:02 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:21:03 | Music Video Player] Search: No results found matching: Juicy - Doja Cat
[INFO @ 08:21:03 | Music Video Player] Searching with URL: https://www.youtube.com/results?disable_polymer=true&search_query=Juicy%20-%20Doja%20Cat
[INFO @ 08:21:04 | Music Video Player] Search: No results found matching: Juicy - Doja Cat

**Comment by gthgame** [comment]
any fix ? yes it's all under window["ytInitialData"] now ...

**Comment by rie-kumar** [comment]
Should be a fix tomorrow. 

Nevermind, @b-rad15 already fixed it.

**Comment by b-rad15** [comment]
This should be mostly fixed but youtube-dl not updating causes some issues related to this now as it handles the searching as described by #18
