### ISSUE TITLE
Add the ability to select a specific video by entering the Youtube ID

### ISSUE THREAD

**Issue by leinstay** [rie-kumar/MusicVideoPlayer#20]
Thank you for this modification, my viewers are now much more happy to spend time on the stream, and my mapmakers can directly attach video files to the maps.

Unfortunately, I have found that the search hardly works, either it's empty or it finds the wrong videos (example: https://imgur.com/a/9u6bmLv), and I can't use non-English characters in the search.

Is it possible to add a small field in which I can enter the id of the video (my viewers will search for the desired video) and bypass search?

**Comment by pdkim1087** [comment]
Maybe not necessarily the youtube ID but just getting the search to work properly would go a long ways to making it usable.  :)

**Comment by b-rad15** [comment]
That's a good idea as a fallback, I think I could do that pretty easily

**Comment by b-rad15** [comment]
Should be in the next build I push, start the search with v= and then it will read the id

**Comment by b-rad15** [comment]
working, intentionally minimal to prevent issues
