### ISSUE TITLE
No results from search

### ISSUE THREAD

**Issue by eg0071** [rie-kumar/MusicVideoPlayer#28]
It seems that this just started happening today. Yesterday it was fine. Re-installed etc. Still no results from search. Tried many different songs. 
Thanks for your help.

**Comment by b-rad15** [comment]
Looks like youtube-dl was updated and #18 is rearing its ugly head, can you copy the file youtube-dl-updater.bat here if it exists in the Youtube-dl folder?

**Comment by eg0071** [comment]
Hi b-rad15 I don't appear to have the youtube-dl-updater.bat in the Youtube-dl folder.
There is 

concat.ps1
ffmpeg.exe
SelectJsonFromYoutubeDL.exe
youtube-dl.exe


Thanks

**Comment by eg0071** [comment]
Btw this is a fantastic mod. My fav.

**Comment by b-rad15** [comment]
Huh, interesting, I just tried it on my machine and search seems to be working, can you try running opening that folder, shift+right click then either open powershell here or open cmd prompt here, then run the command "youtube-dl.exe --version" and paste what the output is?

**Comment by eg0071** [comment]
2020.09.06

**Comment by eg0071** [comment]
I can see 
youtube-dl.exe.new 
in the directory

**Comment by eg0071** [comment]
I tried deleting the youtube-dl.exe and youtube-dl.exe.new and reinstalled and it appears to be working again. So not sure if that was what fixed it. Ty.

**Comment by b-rad15** [comment]
ok so yeah thats the issue I'm talking about, it creates the youtube-dl.exe.new but cant copy that to youtube-dl.exe, I think I can try to delete youtube-dl.exe and then rename youtube-dl.exe.new but I'm not sure that will work and it'll be tough to test, worst case I update youtube-dl manually when i push the update

**Comment by eg0071** [comment]
Thank you very much for your help. Happy to help test if that is feasible.

**Comment by b-rad15** [comment]
should be fixed now on the release I'm putting in now

**Comment by eg0071** [comment]
Thank you :)

**Comment by b-rad15** [comment]
No Problem, next time you get a chance to play the game, if it's working just hit the close button at the bottom here or mention it if you don't have the option to close this
