### ISSUE TITLE
Ability to not have the screen rotate in 90/360 mode?

### ISSUE THREAD

**Issue by SenseiPSK** [rie-kumar/MusicVideoPlayer#30]
I'm sorry if this is the wrong place to suggest this. Would it be possible to add an option to keep the screen centered in the middle position instead of turning in either the 90 or 360 degree modes? It does look good, but when filming with a fixed camera behind the player it would be better if the video stayed in one place. Maybe there could be just a toggle or something for it, or another position option that is just called "fixed"?

**Comment by b-rad15** [comment]
Yeah I don't that would be too tough

**Comment by b-rad15** [comment]
Done, will be in next build
