### ISSUE TITLE
Music from a different song starts playing after pausing the game

### ISSUE THREAD

**Issue by Kevga** [rie-kumar/MusicVideoPlayer#32]
How to reproduce:

1. Launch Beat Saber
2. Select a song with a configured video and press the "Preview" button
3. While the preview is playing, select a different song without a configured video
4. Start playing the song for a few seconds
5. Pause the song and press continue

After that, the music from the song that was previewed starts playing in addition to the song you are currently playing.

Game Version: 1.11.1
Plugin Version: 1.11.2 (also happened with 1.11.1, it's not a recent regression)

**Comment by b-rad15** [comment]
Thought I fixed this a little bit ago but I guess not. easy fix is to mute audio like I did before but tough fix is to unload the video from the screen which I thought I did but I guess not

**Comment by b-rad15** [comment]
#10

**Comment by b-rad15** [comment]
Should be fixed in next build, I realized what the issue was with playing, video should no longer play, I am not sure if unloading the video is possible
