### ISSUE TITLE
Setting to turn off audio?

### ISSUE THREAD

**Issue by 203Null** [rie-kumar/MusicVideoPlayer#6]
I don't think anyone needs duplicated audio. Currently, I have to manually remove audio from every single video.
Also, my download isn't working, it stucks at "Loading Results..."

**Comment by b-rad15** [comment]
fixed in latest build
For the download thing if it's still happening open up another issue

**Comment by b-rad15** [comment]
Nevermind the audio on a video just glitched

**Comment by b-rad15** [comment]
Ok should be fixed now
